/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Administrador;
import Clases.Cola;
import Clases.InteligenciaArtificial;
import Clases.Personaje;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaSimulacion extends javax.swing.JFrame {
    public static Administrador admin;
    public static InteligenciaArtificial ia;
    public static Personaje competidor;
    public static int idDistintivoNK;
    public static int idDistintivoCN;
    public static long tiempoDecision;
    public static int contadorCombates;
    //Colas Nickelodeon
    public static Cola colaExcepcionalesNK;
    public static Cola colaPromediosNK;
    public static Cola colaDeficientesNK;
    public static Cola colaRefuerzoNK;
    //Colas Cartoon Network
    public static Cola colaExcepcionalesCN;
    public static Cola colaPromediosCN;
    public static Cola colaDeficientesCN;
    public static Cola colaRefuerzoCN;
    
    public static Personaje[] personajesInicialesNK;
    public static Personaje[] personajesInicialesCN;
    
    
    
    
    public VentanaSimulacion() {
        initComponents();
        this.idDistintivoCN = 0;
        this.idDistintivoCN = 0;
        this.tiempoDecision = 10;
        this.contadorCombates = 0;
        this.personajesInicialesNK = new Personaje[20];
        this.personajesInicialesCN = new Personaje[20];
        this.admin = new Administrador();
        this.ia = new InteligenciaArtificial();
        // Creacion Colas Nickelodeon
        this.colaExcepcionalesNK = new Cola();
        this.colaPromediosNK = new Cola();
        this.colaDeficientesNK = new Cola();
        this.colaRefuerzoNK = new Cola();
        // Creacion Colas Cartoon Network
        this.colaExcepcionalesCN = new Cola();
        this.colaPromediosCN = new Cola();
        this.colaDeficientesCN = new Cola();
        this.colaRefuerzoCN = new Cola();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        JLabel37 = new javax.swing.JLabel();
        JLabel38 = new javax.swing.JLabel();
        JLabel39 = new javax.swing.JLabel();
        tiempo = new javax.swing.JToggleButton();
        iniciar = new javax.swing.JToggleButton();
        cantidadCola1NK = new javax.swing.JLabel();
        contadorCola3Avatar = new javax.swing.JLabel();
        cantidadCola2NK = new javax.swing.JLabel();
        JLabel40 = new javax.swing.JLabel();
        JLabel41 = new javax.swing.JLabel();
        JLabel42 = new javax.swing.JLabel();
        cantidadCola3CN = new javax.swing.JLabel();
        cantidadCola1CN = new javax.swing.JLabel();
        cantidadCola2CN = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ganador = new javax.swing.JLabel();
        idNK = new javax.swing.JLabel();
        idCN = new javax.swing.JLabel();
        cantidadHabilidadesCN = new javax.swing.JLabel();
        JLabel50 = new javax.swing.JLabel();
        JLabel52 = new javax.swing.JLabel();
        JLabel53 = new javax.swing.JLabel();
        vidaCN = new javax.swing.JLabel();
        agilidadCN = new javax.swing.JLabel();
        fuerzaCN = new javax.swing.JLabel();
        JLabel51 = new javax.swing.JLabel();
        JLabel54 = new javax.swing.JLabel();
        cantidadHabilidadesNK = new javax.swing.JLabel();
        JLabel55 = new javax.swing.JLabel();
        vidaNK = new javax.swing.JLabel();
        JLabel56 = new javax.swing.JLabel();
        fuerzaNK = new javax.swing.JLabel();
        JLabel57 = new javax.swing.JLabel();
        agilidadNK = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidadCola3NK = new javax.swing.JLabel();
        contadorCola2Avatar = new javax.swing.JLabel();
        contadorCola2Show = new javax.swing.JLabel();
        contadorCola3Show = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        estadoIA = new javax.swing.JLabel();
        estadoAdmin = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialGanadores = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cola3NK = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        cola3CN = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        cola2NK = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cola1NK = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        cola1CN = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        cola2CN = new javax.swing.JTextArea();
        progresoTiempo = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colaRefuerzoShow = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        colaRefuerzoAvatar = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        calidadNK = new javax.swing.JLabel();
        calidadCN = new javax.swing.JLabel();
        habilidadesCN = new javax.swing.JLabel();
        habilidadesNK = new javax.swing.JLabel();
        nombreNK = new javax.swing.JLabel();
        nombreCN = new javax.swing.JLabel();
        fondoPersonajeNK = new javax.swing.JTextArea();
        fondoPersonajeCN = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        tituloAVA = new javax.swing.JTextArea();
        tituloRS = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(0, 51, 204));
        Panel.setMinimumSize(new java.awt.Dimension(1100, 700));
        Panel.setPreferredSize(new java.awt.Dimension(1100, 700));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Colas");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 24));

        jLabel36.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Total");
        Panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        JLabel37.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel37.setForeground(new java.awt.Color(255, 255, 255));
        JLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel37.setText("#3");
        Panel.add(JLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 24));

        JLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel38.setForeground(new java.awt.Color(255, 255, 255));
        JLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel38.setText("#2");
        Panel.add(JLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 60, 24));

        JLabel39.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel39.setForeground(new java.awt.Color(255, 255, 255));
        JLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel39.setText("#1");
        Panel.add(JLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 60, 24));

        tiempo.setBackground(new java.awt.Color(255, 153, 0));
        tiempo.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 24)); // NOI18N
        tiempo.setForeground(new java.awt.Color(0, 0, 0));
        tiempo.setText(">>>> TIEMPO <<<<");
        tiempo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        Panel.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 280, 50));

        iniciar.setBackground(new java.awt.Color(255, 153, 0));
        iniciar.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 24)); // NOI18N
        iniciar.setForeground(new java.awt.Color(0, 0, 0));
        iniciar.setText(" >>>> INICIAR <<<<");
        iniciar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        Panel.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 280, 50));

        cantidadCola1NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola1NK.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola1NK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola1NK.setText("0");
        Panel.add(cantidadCola1NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, 20));

        contadorCola3Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 12)); // NOI18N
        contadorCola3Avatar.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola3Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola3Avatar.setText("0");
        Panel.add(contadorCola3Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 20));

        cantidadCola2NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola2NK.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola2NK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola2NK.setText("0");
        Panel.add(cantidadCola2NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 20));

        JLabel40.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel40.setForeground(new java.awt.Color(255, 255, 255));
        JLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel40.setText("#1");
        Panel.add(JLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 60, 24));

        JLabel41.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel41.setForeground(new java.awt.Color(255, 255, 255));
        JLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel41.setText("#2");
        Panel.add(JLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 60, 24));

        JLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel42.setForeground(new java.awt.Color(255, 255, 255));
        JLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel42.setText("#3");
        Panel.add(JLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 60, 24));

        cantidadCola3CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola3CN.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola3CN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola3CN.setText("0");
        Panel.add(cantidadCola3CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 60, 20));

        cantidadCola1CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola1CN.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola1CN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola1CN.setText("0");
        Panel.add(cantidadCola1CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 60, 20));

        cantidadCola2CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola2CN.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola2CN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola2CN.setText("0");
        Panel.add(cantidadCola2CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 60, 20));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MULTIVERSE SHOWDOWN");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        ganador.setBackground(new java.awt.Color(255, 255, 255));
        ganador.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        ganador.setForeground(new java.awt.Color(255, 255, 255));
        ganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganador.setText("...");
        Panel.add(ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 130, 40));

        idNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        idNK.setForeground(new java.awt.Color(255, 255, 255));
        idNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idNK.setText("NK--");
        idNK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(idNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 50, 30));

        idCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        idCN.setForeground(new java.awt.Color(255, 255, 255));
        idCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCN.setText("CN--");
        idCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(idCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 50, 30));

        cantidadHabilidadesCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        cantidadHabilidadesCN.setForeground(new java.awt.Color(255, 255, 255));
        cantidadHabilidadesCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadHabilidadesCN.setText("----");
        cantidadHabilidadesCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(cantidadHabilidadesCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 40, 30));

        JLabel50.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel50.setForeground(new java.awt.Color(255, 255, 255));
        JLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/habilidadesicon.png"))); // NOI18N
        JLabel50.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 30, 30));

        JLabel52.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel52.setForeground(new java.awt.Color(255, 255, 255));
        JLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vidaicon.png"))); // NOI18N
        JLabel52.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 30, 30));

        JLabel53.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel53.setForeground(new java.awt.Color(255, 255, 255));
        JLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agilidadicon.png"))); // NOI18N
        JLabel53.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 30, 30));

        vidaCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        vidaCN.setForeground(new java.awt.Color(255, 255, 255));
        vidaCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaCN.setText("----");
        vidaCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(vidaCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 50, 30));

        agilidadCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        agilidadCN.setForeground(new java.awt.Color(255, 255, 255));
        agilidadCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilidadCN.setText("----");
        agilidadCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(agilidadCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 50, 30));

        fuerzaCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        fuerzaCN.setForeground(new java.awt.Color(255, 255, 255));
        fuerzaCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuerzaCN.setText("----");
        fuerzaCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(fuerzaCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 40, 30));

        JLabel51.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel51.setForeground(new java.awt.Color(255, 255, 255));
        JLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuerzaicon.png"))); // NOI18N
        JLabel51.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 30, 30));

        JLabel54.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel54.setForeground(new java.awt.Color(255, 255, 255));
        JLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/habilidadesicon.png"))); // NOI18N
        JLabel54.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 30, 30));

        cantidadHabilidadesNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        cantidadHabilidadesNK.setForeground(new java.awt.Color(255, 255, 255));
        cantidadHabilidadesNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadHabilidadesNK.setText("----");
        cantidadHabilidadesNK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(cantidadHabilidadesNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 40, 30));

        JLabel55.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel55.setForeground(new java.awt.Color(255, 255, 255));
        JLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vidaicon.png"))); // NOI18N
        JLabel55.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 30, 30));

        vidaNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        vidaNK.setForeground(new java.awt.Color(255, 255, 255));
        vidaNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaNK.setText("----");
        vidaNK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(vidaNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 50, 30));

        JLabel56.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel56.setForeground(new java.awt.Color(255, 255, 255));
        JLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuerzaicon.png"))); // NOI18N
        JLabel56.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 30, 30));

        fuerzaNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        fuerzaNK.setForeground(new java.awt.Color(255, 255, 255));
        fuerzaNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuerzaNK.setText("----");
        fuerzaNK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(fuerzaNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 40, 30));

        JLabel57.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        JLabel57.setForeground(new java.awt.Color(255, 255, 255));
        JLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agilidadicon.png"))); // NOI18N
        JLabel57.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(JLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 30, 30));

        agilidadNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        agilidadNK.setForeground(new java.awt.Color(255, 255, 255));
        agilidadNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilidadNK.setText("----");
        agilidadNK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel.add(agilidadNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 50, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 42)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("VS");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 70, 150));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contador");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        cantidadCola3NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola3NK.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola3NK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola3NK.setText("0");
        Panel.add(cantidadCola3NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 20));

        contadorCola2Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola2Avatar.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola2Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola2Avatar.setText("0");
        Panel.add(contadorCola2Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 20));

        contadorCola2Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola2Show.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola2Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola2Show.setText("0");
        Panel.add(contadorCola2Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 60, 20));

        contadorCola3Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola3Show.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola3Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola3Show.setText("0");
        Panel.add(contadorCola3Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 60, 20));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IA ...");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 30));

        estadoIA.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        estadoIA.setForeground(new java.awt.Color(255, 204, 51));
        estadoIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoIA.setText("- - - -");
        Panel.add(estadoIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 170, 30));

        estadoAdmin.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        estadoAdmin.setForeground(new java.awt.Color(255, 204, 51));
        estadoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoAdmin.setText("- - - -");
        Panel.add(estadoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 170, 30));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("ADMIN ...");
        Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 100, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        historialGanadores.setEditable(false);
        historialGanadores.setBackground(new java.awt.Color(51, 51, 51));
        historialGanadores.setColumns(20);
        historialGanadores.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        historialGanadores.setForeground(new java.awt.Color(255, 204, 51));
        historialGanadores.setRows(5);
        historialGanadores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(historialGanadores);
        historialGanadores.getAccessibleContext().setAccessibleDescription("");

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 220, 100));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola3NK.setEditable(false);
        cola3NK.setBackground(new java.awt.Color(51, 51, 51));
        cola3NK.setColumns(20);
        cola3NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola3NK.setForeground(new java.awt.Color(255, 204, 51));
        cola3NK.setRows(5);
        cola3NK.setAutoscrolls(false);
        cola3NK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(cola3NK);

        Panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, 240));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola3CN.setEditable(false);
        cola3CN.setBackground(new java.awt.Color(51, 51, 51));
        cola3CN.setColumns(20);
        cola3CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola3CN.setForeground(new java.awt.Color(255, 204, 51));
        cola3CN.setRows(5);
        cola3CN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane5.setViewportView(cola3CN);

        Panel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 60, 240));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola2NK.setEditable(false);
        cola2NK.setBackground(new java.awt.Color(51, 51, 51));
        cola2NK.setColumns(20);
        cola2NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola2NK.setForeground(new java.awt.Color(255, 204, 51));
        cola2NK.setRows(5);
        cola2NK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane6.setViewportView(cola2NK);

        Panel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 240));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("C");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, 37));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("N");
        Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 37));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola1NK.setEditable(false);
        cola1NK.setBackground(new java.awt.Color(51, 51, 51));
        cola1NK.setColumns(20);
        cola1NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola1NK.setForeground(new java.awt.Color(255, 204, 51));
        cola1NK.setRows(5);
        cola1NK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane7.setViewportView(cola1NK);

        Panel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 60, 240));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola1CN.setEditable(false);
        cola1CN.setBackground(new java.awt.Color(51, 51, 51));
        cola1CN.setColumns(20);
        cola1CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola1CN.setForeground(new java.awt.Color(255, 204, 51));
        cola1CN.setRows(5);
        cola1CN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane8.setViewportView(cola1CN);

        Panel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 60, 240));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cola2CN.setEditable(false);
        cola2CN.setBackground(new java.awt.Color(51, 51, 51));
        cola2CN.setColumns(20);
        cola2CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola2CN.setForeground(new java.awt.Color(255, 204, 51));
        cola2CN.setRows(5);
        cola2CN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane9.setViewportView(cola2CN);

        Panel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 60, 240));
        Panel.add(progresoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 240, 30));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Refuerzo");
        Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 60, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Refuerzo");
        Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 60, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        colaRefuerzoShow.setEditable(false);
        colaRefuerzoShow.setBackground(new java.awt.Color(51, 51, 51));
        colaRefuerzoShow.setColumns(20);
        colaRefuerzoShow.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        colaRefuerzoShow.setForeground(new java.awt.Color(255, 204, 51));
        colaRefuerzoShow.setRows(5);
        colaRefuerzoShow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(colaRefuerzoShow);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 60, 150));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        colaRefuerzoAvatar.setEditable(false);
        colaRefuerzoAvatar.setBackground(new java.awt.Color(51, 51, 51));
        colaRefuerzoAvatar.setColumns(20);
        colaRefuerzoAvatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        colaRefuerzoAvatar.setForeground(new java.awt.Color(255, 204, 51));
        colaRefuerzoAvatar.setRows(5);
        colaRefuerzoAvatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(colaRefuerzoAvatar);

        Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 150));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Historial de Ganadores");
        Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 220, -1));

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 204, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("K");
        Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 37));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("E");
        Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 40, 37));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("L");
        Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 37));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 40, 37));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("I");
        Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, 37));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 204, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("O");
        Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 37));

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 204, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("N");
        Panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 40, 37));

        jLabel30.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 204, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("A");
        Panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 40, 37));

        jLabel29.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 204, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("N");
        Panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 40, 37));

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 204, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("O");
        Panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 40, 37));

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 204, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("O");
        Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 40, 37));

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 204, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("T");
        Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 40, 37));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 204, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("C");
        Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 40, 37));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 204, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("R");
        Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 40, 37));

        calidadNK.setBackground(new java.awt.Color(0, 0, 0));
        calidadNK.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        calidadNK.setForeground(new java.awt.Color(255, 255, 255));
        calidadNK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calidadNK.setText("- - - -");
        Panel.add(calidadNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 120, 40));

        calidadCN.setBackground(new java.awt.Color(0, 0, 0));
        calidadCN.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        calidadCN.setForeground(new java.awt.Color(255, 255, 255));
        calidadCN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calidadCN.setText("- - - -");
        Panel.add(calidadCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 130, 40));

        habilidadesCN.setBackground(new java.awt.Color(255, 153, 0));
        habilidadesCN.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 12)); // NOI18N
        habilidadesCN.setForeground(new java.awt.Color(255, 153, 0));
        habilidadesCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habilidadesCN.setText("(- - -/- - -/- - -)");
        Panel.add(habilidadesCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 160, 40));

        habilidadesNK.setBackground(new java.awt.Color(255, 153, 0));
        habilidadesNK.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 12)); // NOI18N
        habilidadesNK.setForeground(new java.awt.Color(255, 153, 0));
        habilidadesNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habilidadesNK.setText("(- - -/- - -/- - -)");
        Panel.add(habilidadesNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 160, 40));

        nombreNK.setBackground(new java.awt.Color(255, 153, 0));
        nombreNK.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 30)); // NOI18N
        nombreNK.setForeground(new java.awt.Color(255, 153, 0));
        nombreNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreNK.setText("----");
        nombreNK.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        Panel.add(nombreNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 160, 150));

        nombreCN.setBackground(new java.awt.Color(255, 153, 0));
        nombreCN.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 30)); // NOI18N
        nombreCN.setForeground(new java.awt.Color(255, 153, 0));
        nombreCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCN.setText("----");
        nombreCN.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        Panel.add(nombreCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 160, 150));

        fondoPersonajeNK.setEditable(false);
        fondoPersonajeNK.setBackground(new java.awt.Color(51, 51, 51));
        fondoPersonajeNK.setColumns(20);
        fondoPersonajeNK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fondoPersonajeNK.setForeground(new java.awt.Color(0, 0, 0));
        fondoPersonajeNK.setRows(5);
        Panel.add(fondoPersonajeNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 160, 150));

        fondoPersonajeCN.setEditable(false);
        fondoPersonajeCN.setBackground(new java.awt.Color(51, 51, 51));
        fondoPersonajeCN.setColumns(20);
        fondoPersonajeCN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fondoPersonajeCN.setForeground(new java.awt.Color(0, 0, 0));
        fondoPersonajeCN.setRows(5);
        Panel.add(fondoPersonajeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 160, 150));

        jLabel38.setBackground(new java.awt.Color(255, 153, 0));
        jLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 48)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 153, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Avatar");
        jLabel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 310, 60));

        jLabel33.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("RESULTADO");
        Panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 601, 350, 40));

        jLabel47.setBackground(new java.awt.Color(255, 153, 0));
        jLabel47.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 48)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 153, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Regular Show");
        jLabel47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 340, 60));

        tituloAVA.setEditable(false);
        tituloAVA.setBackground(new java.awt.Color(51, 51, 51));
        tituloAVA.setColumns(20);
        tituloAVA.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        tituloAVA.setForeground(new java.awt.Color(0, 0, 0));
        tituloAVA.setRows(5);
        Panel.add(tituloAVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 310, 60));

        tituloRS.setEditable(false);
        tituloRS.setBackground(new java.awt.Color(51, 51, 51));
        tituloRS.setColumns(20);
        tituloRS.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        tituloRS.setForeground(new java.awt.Color(0, 0, 0));
        tituloRS.setRows(5);
        Panel.add(tituloRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 340, 60));

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 204, 51));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("D");
        Panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 40, 37));

        jLabel39.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 51));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("E");
        Panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, 37));

        jLabel40.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 204, 51));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("O");
        Panel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, 37));

        jLabel41.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 204, 51));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("E");
        Panel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 40, 37));

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 204, 51));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("W");
        Panel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 40, 37));

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 204, 51));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("T");
        Panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 40, 37));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 204, 51));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("O");
        Panel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 40, 37));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 204, 51));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("K");
        Panel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, 40, 37));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 204, 51));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("R");
        Panel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 40, 37));

        fondo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        Panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        ia.tiempoDecision();
        
        
    }//GEN-LAST:event_tiempoActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        iniciar.setEnabled(false);
        admin.creacionPersonajesIniciales();
        admin.mostrarPersonajesIniciales();
        admin.llenarColasIniciales();
        ia.start();
        
        System.out.println("COLA ENK");
        String contenidoENK = colaExcepcionalesNK.recorrido();
        System.out.println(contenidoENK);
        System.out.println("COLA PNK");
        String contenidoPNK = colaPromediosNK.recorrido();
        System.out.println(contenidoPNK);
        System.out.println("COLA DNK");
        String contenidoDNK = colaDeficientesNK.recorrido();
        System.out.println(contenidoDNK);
        
        System.out.println("COLA ECN");
        String contenidoECN = colaExcepcionalesCN.recorrido();
        System.out.println(contenidoECN);
        System.out.println("COLA PCN");
        String contenidoPCN = colaPromediosCN.recorrido();
        System.out.println(contenidoPCN);
        System.out.println("COLA DCN");
        String contenidoDCN = colaDeficientesCN.recorrido();
        System.out.println(contenidoDCN);
        
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel37;
    private javax.swing.JLabel JLabel38;
    private javax.swing.JLabel JLabel39;
    private javax.swing.JLabel JLabel40;
    private javax.swing.JLabel JLabel41;
    private javax.swing.JLabel JLabel42;
    public static javax.swing.JLabel JLabel50;
    public static javax.swing.JLabel JLabel51;
    public static javax.swing.JLabel JLabel52;
    public static javax.swing.JLabel JLabel53;
    public static javax.swing.JLabel JLabel54;
    public static javax.swing.JLabel JLabel55;
    public static javax.swing.JLabel JLabel56;
    public static javax.swing.JLabel JLabel57;
    private javax.swing.JPanel Panel;
    public static javax.swing.JLabel agilidadCN;
    public static javax.swing.JLabel agilidadNK;
    public static javax.swing.JLabel calidadCN;
    public static javax.swing.JLabel calidadNK;
    public static javax.swing.JLabel cantidadCola1CN;
    public static javax.swing.JLabel cantidadCola1NK;
    public static javax.swing.JLabel cantidadCola2CN;
    public static javax.swing.JLabel cantidadCola2NK;
    public static javax.swing.JLabel cantidadCola3CN;
    public static javax.swing.JLabel cantidadCola3NK;
    public static javax.swing.JLabel cantidadHabilidadesCN;
    public static javax.swing.JLabel cantidadHabilidadesNK;
    public static javax.swing.JTextArea cola1CN;
    public static javax.swing.JTextArea cola1NK;
    public static javax.swing.JTextArea cola2CN;
    public static javax.swing.JTextArea cola2NK;
    public static javax.swing.JTextArea cola3CN;
    public static javax.swing.JTextArea cola3NK;
    public static javax.swing.JTextArea colaRefuerzoAvatar;
    public static javax.swing.JTextArea colaRefuerzoShow;
    public static javax.swing.JLabel contadorCola2Avatar;
    public static javax.swing.JLabel contadorCola2Show;
    public static javax.swing.JLabel contadorCola3Avatar;
    public static javax.swing.JLabel contadorCola3Show;
    private javax.swing.JLabel estadoAdmin;
    public static javax.swing.JLabel estadoIA;
    private javax.swing.JLabel fondo;
    public static javax.swing.JTextArea fondoPersonajeCN;
    public static javax.swing.JTextArea fondoPersonajeNK;
    public static javax.swing.JLabel fuerzaCN;
    public static javax.swing.JLabel fuerzaNK;
    public static javax.swing.JLabel ganador;
    public static javax.swing.JLabel habilidadesCN;
    public static javax.swing.JLabel habilidadesNK;
    public static javax.swing.JTextArea historialGanadores;
    public static javax.swing.JLabel idCN;
    public static javax.swing.JLabel idNK;
    private javax.swing.JToggleButton iniciar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JLabel nombreCN;
    public static javax.swing.JLabel nombreNK;
    public static javax.swing.JProgressBar progresoTiempo;
    private javax.swing.JToggleButton tiempo;
    public static javax.swing.JTextArea tituloAVA;
    public static javax.swing.JTextArea tituloRS;
    public static javax.swing.JLabel vidaCN;
    public static javax.swing.JLabel vidaNK;
    // End of variables declaration//GEN-END:variables
}
