/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Administrador;
import Clases.Cola;
import Clases.Personaje;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaSimulacion extends javax.swing.JFrame {
    public static Administrador admin;
    public static Personaje competidor;
    public static int idDistintivoNK;
    public static int idDistintivoCN;
    //Colas Nickelodeon
    public static Cola colaExcepcionalesNK;
    public static Cola colaPromediosNK;
    public static Cola colaDeficientesNK;
    public static Cola colaRefuerzoNK;
    //Colas Cartoon Network
    public static Cola colaExcepcionalesCN;
    public static Cola colaPromediosCN;
    public static Cola colaDeficientesCN;
    public static Cola colaRefuerzoCN;
    
    public static Personaje[] personajesInicialesNK;
    public static Personaje[] personajesInicialesCN;
    
    
    
    
    public VentanaSimulacion() {
        initComponents();
        this.idDistintivoCN = 0;
        this.idDistintivoCN = 0;
        this.personajesInicialesNK = new Personaje[20];
        this.personajesInicialesCN = new Personaje[20];
        this.admin = new Administrador();
        // Creacion Colas Nickelodeon
        this.colaExcepcionalesNK = new Cola();
        this.colaPromediosNK = new Cola();
        this.colaDeficientesNK = new Cola();
        this.colaRefuerzoNK = new Cola();
        // Creacion Colas Cartoon Network
        this.colaExcepcionalesCN = new Cola();
        this.colaPromediosCN = new Cola();
        this.colaDeficientesCN = new Cola();
        this.colaRefuerzoCN = new Cola();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        JLabel37 = new javax.swing.JLabel();
        JLabel38 = new javax.swing.JLabel();
        JLabel39 = new javax.swing.JLabel();
        tiempo = new javax.swing.JToggleButton();
        iniciar = new javax.swing.JToggleButton();
        cantidadCola1Avatar = new javax.swing.JLabel();
        contadorCola3Avatar = new javax.swing.JLabel();
        cantidadCola2Avatar = new javax.swing.JLabel();
        JLabel40 = new javax.swing.JLabel();
        JLabel41 = new javax.swing.JLabel();
        JLabel42 = new javax.swing.JLabel();
        cantidadCola3Show = new javax.swing.JLabel();
        cantidadCola1Show = new javax.swing.JLabel();
        cantidadCola2Show = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        desicion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idShow = new javax.swing.JLabel();
        idAvatar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidadCola3Avatar = new javax.swing.JLabel();
        contadorCola2Avatar = new javax.swing.JLabel();
        contadorCola2Show = new javax.swing.JLabel();
        contadorCola3Show = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialGanadores = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cola3NK = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        cola3CN = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        cola2NK = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cola1NK = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        cola1CN = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        cola2CN = new javax.swing.JTextArea();
        progresoTiempo = new javax.swing.JProgressBar();
        puntosAvatar = new javax.swing.JLabel();
        puntosShow = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colaRefuerzoShow = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        colaRefuerzoAvatar = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        fotoCopaIzq = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        calidadPersonajeNK = new javax.swing.JLabel();
        calidadPersonajeCN = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        habilidadesAvatar = new javax.swing.JTextArea();
        habilidadesShow = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        fotoCopaDer = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(0, 51, 204));
        Panel.setMinimumSize(new java.awt.Dimension(1100, 700));
        Panel.setPreferredSize(new java.awt.Dimension(1100, 700));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Colas");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 24));

        jLabel36.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Total");
        Panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        JLabel37.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel37.setForeground(new java.awt.Color(255, 255, 255));
        JLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel37.setText("#3");
        Panel.add(JLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 24));

        JLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel38.setForeground(new java.awt.Color(255, 255, 255));
        JLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel38.setText("#2");
        Panel.add(JLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 24));

        JLabel39.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel39.setForeground(new java.awt.Color(255, 255, 255));
        JLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel39.setText("#1");
        Panel.add(JLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 60, 24));

        tiempo.setBackground(new java.awt.Color(255, 153, 0));
        tiempo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        tiempo.setForeground(new java.awt.Color(255, 255, 255));
        tiempo.setText("Tiempo");
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        Panel.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 180, 30));

        iniciar.setBackground(new java.awt.Color(255, 153, 0));
        iniciar.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setText("BATALLA");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        Panel.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 180, 70));

        cantidadCola1Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola1Avatar.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola1Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola1Avatar.setText("0");
        Panel.add(cantidadCola1Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 60, 20));

        contadorCola3Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 12)); // NOI18N
        contadorCola3Avatar.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola3Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola3Avatar.setText("0");
        Panel.add(contadorCola3Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 20));

        cantidadCola2Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola2Avatar.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola2Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola2Avatar.setText("0");
        Panel.add(cantidadCola2Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 60, 20));

        JLabel40.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel40.setForeground(new java.awt.Color(255, 255, 255));
        JLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel40.setText("#1");
        Panel.add(JLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 60, 24));

        JLabel41.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel41.setForeground(new java.awt.Color(255, 255, 255));
        JLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel41.setText("#2");
        Panel.add(JLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 60, 24));

        JLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        JLabel42.setForeground(new java.awt.Color(255, 255, 255));
        JLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel42.setText("#3");
        Panel.add(JLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 60, 24));

        cantidadCola3Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola3Show.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola3Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola3Show.setText("0");
        Panel.add(cantidadCola3Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 60, 20));

        cantidadCola1Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola1Show.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola1Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola1Show.setText("0");
        Panel.add(cantidadCola1Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 60, 20));

        cantidadCola2Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola2Show.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola2Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola2Show.setText("0");
        Panel.add(cantidadCola2Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 60, 20));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MULTIVERSE SHOWDOWN");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 680, 50));

        desicion.setBackground(new java.awt.Color(255, 255, 255));
        desicion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        desicion.setForeground(new java.awt.Color(255, 255, 255));
        desicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desicion.setText("...");
        Panel.add(desicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 200, 20));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ID");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 20, 20));

        idShow.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        idShow.setForeground(new java.awt.Color(255, 255, 255));
        idShow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel.add(idShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 100, 20));

        idAvatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        idAvatar.setForeground(new java.awt.Color(255, 255, 255));
        idAvatar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Panel.add(idAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 100, 20));

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("VS");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 80, 130));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contador");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        cantidadCola3Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cantidadCola3Avatar.setForeground(new java.awt.Color(255, 255, 255));
        cantidadCola3Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCola3Avatar.setText("0");
        Panel.add(cantidadCola3Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));

        contadorCola2Avatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola2Avatar.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola2Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola2Avatar.setText("0");
        Panel.add(contadorCola2Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 20));

        contadorCola2Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola2Show.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola2Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola2Show.setText("0");
        Panel.add(contadorCola2Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 60, 20));

        contadorCola3Show.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        contadorCola3Show.setForeground(new java.awt.Color(255, 255, 255));
        contadorCola3Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorCola3Show.setText("0");
        Panel.add(contadorCola3Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 60, 20));

        historialGanadores.setEditable(false);
        historialGanadores.setBackground(new java.awt.Color(255, 255, 255));
        historialGanadores.setColumns(20);
        historialGanadores.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        historialGanadores.setForeground(new java.awt.Color(0, 0, 0));
        historialGanadores.setRows(5);
        jScrollPane1.setViewportView(historialGanadores);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 200, 130));

        cola3NK.setEditable(false);
        cola3NK.setBackground(new java.awt.Color(255, 255, 255));
        cola3NK.setColumns(20);
        cola3NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola3NK.setForeground(new java.awt.Color(0, 0, 0));
        cola3NK.setRows(5);
        jScrollPane4.setViewportView(cola3NK);

        Panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 240));

        cola3CN.setEditable(false);
        cola3CN.setBackground(new java.awt.Color(255, 255, 255));
        cola3CN.setColumns(20);
        cola3CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola3CN.setForeground(new java.awt.Color(0, 0, 0));
        cola3CN.setRows(5);
        jScrollPane5.setViewportView(cola3CN);

        Panel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 60, 240));

        cola2NK.setEditable(false);
        cola2NK.setBackground(new java.awt.Color(255, 255, 255));
        cola2NK.setColumns(20);
        cola2NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola2NK.setForeground(new java.awt.Color(0, 0, 0));
        cola2NK.setRows(5);
        jScrollPane6.setViewportView(cola2NK);

        Panel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 240));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("C");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, 37));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("N");
        Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 37));

        cola1NK.setEditable(false);
        cola1NK.setBackground(new java.awt.Color(255, 255, 255));
        cola1NK.setColumns(20);
        cola1NK.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola1NK.setForeground(new java.awt.Color(0, 0, 0));
        cola1NK.setRows(5);
        jScrollPane7.setViewportView(cola1NK);

        Panel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, 240));

        cola1CN.setEditable(false);
        cola1CN.setBackground(new java.awt.Color(255, 255, 255));
        cola1CN.setColumns(20);
        cola1CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola1CN.setForeground(new java.awt.Color(0, 0, 0));
        cola1CN.setRows(5);
        jScrollPane8.setViewportView(cola1CN);

        Panel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 60, 240));

        cola2CN.setEditable(false);
        cola2CN.setBackground(new java.awt.Color(255, 255, 255));
        cola2CN.setColumns(20);
        cola2CN.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cola2CN.setForeground(new java.awt.Color(0, 0, 0));
        cola2CN.setRows(5);
        jScrollPane9.setViewportView(cola2CN);

        Panel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 60, 240));
        Panel.add(progresoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, 20));

        puntosAvatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        puntosAvatar.setForeground(new java.awt.Color(255, 204, 51));
        puntosAvatar.setText("0");
        Panel.add(puntosAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 100, 20));

        puntosShow.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        puntosShow.setForeground(new java.awt.Color(255, 204, 51));
        puntosShow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        puntosShow.setText("0");
        Panel.add(puntosShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 100, 20));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Refuerzo");
        Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 60, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Refuerzo");
        Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 60, -1));

        colaRefuerzoShow.setEditable(false);
        colaRefuerzoShow.setBackground(new java.awt.Color(255, 255, 255));
        colaRefuerzoShow.setColumns(20);
        colaRefuerzoShow.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        colaRefuerzoShow.setForeground(new java.awt.Color(0, 0, 0));
        colaRefuerzoShow.setRows(5);
        jScrollPane2.setViewportView(colaRefuerzoShow);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 60, 150));

        colaRefuerzoAvatar.setEditable(false);
        colaRefuerzoAvatar.setBackground(new java.awt.Color(255, 255, 255));
        colaRefuerzoAvatar.setColumns(20);
        colaRefuerzoAvatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        colaRefuerzoAvatar.setForeground(new java.awt.Color(0, 0, 0));
        colaRefuerzoAvatar.setRows(5);
        jScrollPane3.setViewportView(colaRefuerzoAvatar);

        Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 60, 150));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Historial de Ganadores");
        Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 200, -1));

        fotoCopaIzq.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fotoCopaIzq.setForeground(new java.awt.Color(255, 255, 255));
        fotoCopaIzq.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Panel.add(fotoCopaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 30, 20));

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 204, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("K");
        Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, 37));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("E");
        Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 37));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("L");
        Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 40, 37));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, 37));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("I");
        Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 37));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 204, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("O");
        Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 37));

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 204, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("N");
        Panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 40, 37));

        jLabel30.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 204, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("A");
        Panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 40, 37));

        jLabel29.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 204, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("N");
        Panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 40, 37));

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 204, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("O");
        Panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 40, 37));

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 204, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("O");
        Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 40, 37));

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 204, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("T");
        Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 40, 37));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 204, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("C");
        Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 40, 37));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 204, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("R");
        Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 40, 37));

        calidadPersonajeNK.setBackground(new java.awt.Color(0, 0, 0));
        calidadPersonajeNK.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 30)); // NOI18N
        calidadPersonajeNK.setForeground(new java.awt.Color(255, 255, 255));
        calidadPersonajeNK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calidadPersonajeNK.setText("fff");
        Panel.add(calidadPersonajeNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 40, 40));

        calidadPersonajeCN.setBackground(new java.awt.Color(0, 0, 0));
        calidadPersonajeCN.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 30)); // NOI18N
        calidadPersonajeCN.setForeground(new java.awt.Color(255, 255, 255));
        calidadPersonajeCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calidadPersonajeCN.setText("fff");
        Panel.add(calidadPersonajeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 40, 40));

        jLabel37.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Un Show Mas");
        Panel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 90, 20));

        habilidadesAvatar.setEditable(false);
        habilidadesAvatar.setBackground(new java.awt.Color(255, 255, 255));
        habilidadesAvatar.setColumns(20);
        habilidadesAvatar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        habilidadesAvatar.setForeground(new java.awt.Color(0, 0, 0));
        habilidadesAvatar.setRows(5);
        Panel.add(habilidadesAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 170, 160));

        habilidadesShow.setEditable(false);
        habilidadesShow.setBackground(new java.awt.Color(255, 255, 255));
        habilidadesShow.setColumns(20);
        habilidadesShow.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        habilidadesShow.setForeground(new java.awt.Color(0, 0, 0));
        habilidadesShow.setRows(5);
        Panel.add(habilidadesShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 170, 160));

        jLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Avatar ");
        Panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 90, 20));

        jLabel33.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("RESULTADO");
        Panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 200, -1));

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("ID");
        Panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 20, 20));

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 204, 51));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("D");
        Panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 37));

        fotoCopaDer.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fotoCopaDer.setForeground(new java.awt.Color(255, 255, 255));
        fotoCopaDer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel.add(fotoCopaDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 30, 20));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("-");
        Panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 100, 50));

        jLabel39.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 51));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("E");
        Panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 40, 37));

        jLabel40.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 204, 51));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("O");
        Panel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, 37));

        jLabel41.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 204, 51));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("E");
        Panel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 40, 37));

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 204, 51));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("W");
        Panel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 40, 37));

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 204, 51));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("T");
        Panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 40, 37));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 204, 51));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("O");
        Panel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 40, 37));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 204, 51));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("K");
        Panel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, 40, 37));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 204, 51));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("R");
        Panel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 40, 37));

        fondo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        Panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        
    }//GEN-LAST:event_tiempoActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        iniciar.setEnabled(false);
        admin.creacionPersonajesIniciales();
        admin.mostrarPersonajesIniciales();
        admin.llenarColasIniciales();
        
        System.out.println("COLA ENK");
        String contenidoENK = colaExcepcionalesNK.recorrido();
        System.out.println(contenidoENK);
        System.out.println("COLA PNK");
        String contenidoPNK = colaPromediosNK.recorrido();
        System.out.println(contenidoPNK);
        System.out.println("COLA DNK");
        String contenidoDNK = colaDeficientesNK.recorrido();
        System.out.println(contenidoDNK);
        
        System.out.println("COLA ECN");
        String contenidoECN = colaExcepcionalesCN.recorrido();
        System.out.println(contenidoECN);
        System.out.println("COLA PCN");
        String contenidoPCN = colaPromediosCN.recorrido();
        System.out.println(contenidoPCN);
        System.out.println("COLA DCN");
        String contenidoDCN = colaDeficientesCN.recorrido();
        System.out.println(contenidoDCN);
        
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel37;
    private javax.swing.JLabel JLabel38;
    private javax.swing.JLabel JLabel39;
    private javax.swing.JLabel JLabel40;
    private javax.swing.JLabel JLabel41;
    private javax.swing.JLabel JLabel42;
    private javax.swing.JPanel Panel;
    public static javax.swing.JLabel calidadPersonajeCN;
    public static javax.swing.JLabel calidadPersonajeNK;
    public static javax.swing.JLabel cantidadCola1Avatar;
    public static javax.swing.JLabel cantidadCola1Show;
    public static javax.swing.JLabel cantidadCola2Avatar;
    public static javax.swing.JLabel cantidadCola2Show;
    public static javax.swing.JLabel cantidadCola3Avatar;
    public static javax.swing.JLabel cantidadCola3Show;
    public static javax.swing.JTextArea cola1CN;
    public static javax.swing.JTextArea cola1NK;
    public static javax.swing.JTextArea cola2CN;
    public static javax.swing.JTextArea cola2NK;
    public static javax.swing.JTextArea cola3CN;
    public static javax.swing.JTextArea cola3NK;
    public static javax.swing.JTextArea colaRefuerzoAvatar;
    public static javax.swing.JTextArea colaRefuerzoShow;
    public static javax.swing.JLabel contadorCola2Avatar;
    public static javax.swing.JLabel contadorCola2Show;
    public static javax.swing.JLabel contadorCola3Avatar;
    public static javax.swing.JLabel contadorCola3Show;
    public static javax.swing.JLabel desicion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fotoCopaDer;
    private javax.swing.JLabel fotoCopaIzq;
    public static javax.swing.JTextArea habilidadesAvatar;
    public static javax.swing.JTextArea habilidadesShow;
    public static javax.swing.JTextArea historialGanadores;
    public static javax.swing.JLabel idAvatar;
    public static javax.swing.JLabel idShow;
    private javax.swing.JToggleButton iniciar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JProgressBar progresoTiempo;
    public static javax.swing.JLabel puntosAvatar;
    public static javax.swing.JLabel puntosShow;
    private javax.swing.JToggleButton tiempo;
    // End of variables declaration//GEN-END:variables
}
